Messages:
  NoPermission: 'You don''t have permission to use this...'
  Format:
    Singular:
      Days: day
      Hour: hour
      Minute: minute
      Second: second
    Plural:
      Days: days
      Hours: hours
      Minutes: minutes
      Seconds: seconds
Bars:
  example_event_1:
    DisplayName:
      Frames:
      - '&fThe event starts in &c{time}'
      - '&eThe event starts in &c{time}'
      - '&fThe event starts in &c{time}'
      - '&eThe event starts in &c{time}'
      - '&fThe event starts in &c{time}'
      - '&eThe event starts in &c{time}'
      - '&fThe event starts in &c{time}'
      - '&eThe event starts in &c{time}'
      Period: 5
    Time: 3m
    Color: YELLOW
    Style: SEGMENTED_20
    Commands:
    - '[message]&dGet ready, an event will start...'
    AnnouncerMode:
      Enabled: false
      Time: 1h 30m
  example_event_2:
    DisplayName:
      Frames:
      - '&fThe event have started!'
      - '&cThe event have started!'
      - '&fThe event have started!'
      - '&cThe event have started!'
      - '&fThe event have started!'
      - '&cThe event have started!'
      - '&fThe Will finish in &6&l{time}&f!'
      - '&fThe Will finish in &6&l{time}&f!'
      - '&fThe Will finish in &6&l{time}&f!'
      - '&fThe Will finish in &6&l{time}&f!'
      - '&fThe Will finish in &6&l{time}&f!'
      - '&fThe Will finish in &6&l{time}&f!'
      Period: 5
    Time: 3m
    Color: YELLOW
    Style: SEGMENTED_20
    Commands:
    - '[title-subtitle]&a&lThank You;&7&lFor Using BossbarTimer;5;40;5'
    - '[message]&dThank you all for testing :D'
    - '[sound]ENTITY_EXPERIENCE_ORB_PICKUP'
    AnnouncerMode:
      Enabled: false
      Time: 1h 30m
  example_bar_1:
    DisplayName:
      Frames:
      - '&f&lBossBarTimer'
      - '&f&lBossBarTimer'
      - '&f&lBossBarTimer'
      - '&f&lBossBarTimer'
      - '&f&lBossBarTimer'
      - '&f&lBossBarTimer'
      - '&f&lBossBarTimer'
      - '&c&lB&f&lossBarTimer'
      - '&c&lBo&f&lssBarTimer'
      - '&c&lBos&f&lsBarTimer'
      - '&f&lB&c&loss&f&lBarTimer'
      - '&f&lBo&c&lssB&f&larTimer'
      - '&f&lBos&c&lsBa&f&lrTimer'
      - '&f&lBoss&c&lBar&f&lTimer'
      - '&f&lBossB&c&larT&f&limer'
      - '&f&lBossBa&c&lrTi&f&lmer'
      - '&f&lBossBar&c&lTim&f&ler'
      - '&f&lBossBarT&c&lime&f&lr'
      - '&f&lBossBarTi&c&lmer&f&l'
      - '&f&lBossBarTim&c&ler&f&l'
      - '&f&lBossBarTime&c&lr&f&l'
      - '&f&lBossBarTimer'
      - '&f&lBossBarTimer'
      - '&f&lBossBarTimer'
      - '&f&lBossBarTimer'
      - '&f&lBossBarTimer'
      - '&f&lBossBarTimer'
      - '&f&lBossBarTimer'
      Period: 1
    Time: 1m 30s
    Color: YELLOW
    Style: SEGMENTED_20
    AnnouncerMode:
      Enabled: true
      Time: 15m
    Commands:
    - '[message] &7This server uses &eBossBarTimer &7made by &eBy_Jack'
    - '[sound] ENTITY_EXPERIENCE_ORB_PICKUP'
