Bars:
  Event1:
    DisplayName: '&7The event starts in &c{time}'
    Time: 5 s
    Color: GREEN
    Style: SOLID
    AnnouncerMode:
      Enabled: false
      Time: 1h
    Commands:
    - 'bbt start Event2'
    - 'say Event2 starting...'
  Event2:
    DisplayName: '&7The event finishes in &c{time}'
    Time: 1 m
    Color: YELLOW
    Style: SEGMENTED_20
    AnnouncerMode:
      Enabled: false
      Time: 1h
    Commands:
    - 'say Event2 ended... thanks for playing'

Messages:
  Format:
    Singular:
      Days: 'day'
      Hour: 'hour'
      Minute: 'minute'
      Second: 'second'
    Plural:
      Days: 'days'
      Hours: 'hours'
      Minutes: 'minutes'
      Seconds: 'seconds'
